apiVersion: v1
kind: Service
metadata:
  labels:
    service: broker
  name: broker
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    service: broker
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: broker
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: broker
  template:
    metadata:
      labels:
        service: broker
    spec:
      containers:
      - image: confluentinc/cp-kafka:7.3.2
        name: broker
        imagePullPolicy: Always
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_BROKER_ID
        - name: KAFKA_ZOOKEEPER_CONNECT
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_ZOOKEEPER_CONNECT
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        - name: KAFKA_ADVERTISED_LISTENERS
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_ADVERTISED_LISTENERS
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
        - name: KAFKA_LISTENERS
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_LISTENERS